[package]
name = "quark"
version = "0.1.0"
edition = "2021"
description = "Quark: A programming language for quantum computing ğŸŒ"
authors = ["Danial Haseeb", "Rasib Nadeem"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.4", features = ["derive"] }
itertools = "0.12.1"
